export type ApiUrls = {
  GET: {
    CATEGORIES_REPRESSIO: (lang: string) => string;
    MUNICIPI_ID: (id: number) => string;
    ESPAI_ID: (id: number) => string;
  };
  POST: {
    MUNICIPI: string;
    MUNICIPI_ESTAT: string;
    MUNICIPI_COMUNITAT: string;
    MUNICIPI_COMARCA: string;
    CAUSA_MORT: string;
    CATEGORIA_REPRESSIO: string;
    SUB_SECTOR_ECONOMIC: string;
    OFICI: string;
    CARREC_EMPRESA: string;
    ACUSACIO_JUDICIAL: string;
    BANDOL: string;
    CONDICIO_MILITAR: string;
    COS_MILITAR: string;
    ESPAI: string;
    ESTAT_CIVIL: string;
    NIVELL_ESTUDIS: string;
  };
  PUT: {
    MUNICIPI: string;
    MUNICIPI_ESTAT: string;
    MUNICIPI_COMUNITAT: string;
    MUNICIPI_COMARCA: string;
    CAUSA_MORT: string;
    CATEGORIA_REPRESSIO: string;
    SUB_SECTOR_ECONOMIC: string;
    OFICI: string;
    CARREC_EMPRESA: string;
    ACUSACIO_JUDICIAL: string;
    BANDOL: string;
    CONDICIO_MILITAR: string;
    COS_MILITAR: string;
    ESPAI: string;
    ESTAT_CIVIL: string;
    NIVELL_ESTUDIS: string;
  };
  DELETE: {
    MUNICIPI: string;
    MUNICIPI_ESTAT: string;
    MUNICIPI_COMUNITAT: string;
    MUNICIPI_COMARCA: string;
    CAUSA_MORT: string;
    CATEGORIA_REPRESSIO: string;
    SUB_SECTOR_ECONOMIC: string;
    OFICI: string;
    CARREC_EMPRESA: string;
    ACUSACIO_JUDICIAL: string;
    BANDOL: string;
    CONDICIO_MILITAR: string;
    COS_MILITAR: string;
    ESPAI: string;
    ESTAT_CIVIL: string;
    NIVELL_ESTUDIS: string;
  };
};
