export type ApiUrls = {
  GET: {
    CATEGORIES_REPRESSIO: (lang: string) => string;
    MUNICIPI_ID: (id: number) => string;
    ESPAI_ID: (id: number) => string;
    SUB_SECTOR_ID: (id: number) => string;
    SECTOR_ECONOMIC: string;
    CATEGORIA_REPRESSIO_ID: (id: number) => string;
    CAUSA_MORT: string;
    ESPAIS: string;
    ESTAT_CIVIL: string;
    NIVELLS_ESTUDIS: string;
    OFICIS: string;
    CARRECS_EMPRESA: string;
    SUB_SECTORS_ECONOMICS: string;
    ACUSACIONS_JUDICIALS: string;
    BANDOLS: string;
    CONDICIONS_MILITARS: string;
    COSOS_MILITARS: string;
    LLISTAT_BIBLIOGRAFIA: string;
    LLISTAT_ARXIUS: string;
    LLIBRE_ID: (id: number) => string;
    ARXIU_ID: (id: number) => string;
    LLISTAT_EXILIATS: string;
    LLISTAT_DEPORTATS: string;
    LLISTAT_REGISTRES_DUPLICATS: string;
    LLISTAT_MORTS_FRONT: string;
    LLISTAT_MORTS_CIVILS: string;
    LLISTAT_REPRESALIA_REPUBLICANA: string;
    LLISTAT_PROCESSATS: string;
    LLISTAT_AFUSELLATS: string;
    LLISTAT_PRESO_MODEL: string;
    EMPRESA_ID: (id: number) => string;
    EMPRESONAT_ID: (id: number) => string;
    PROCEDIMENTS_JUDICIALS: string;
    TIPUS_JUDICIS: string;
    SENTENCIES: string;
    PENES: string;
    JUTJATS: string;
    MODALITATS_PRESO: string;
    MOTIUS_DETENCIO: string;
    GRUPS_REPRESSIO: string;
    PRESONS: string;
    LLISTAT_CASOS_REVISIO: string;
    LLISTAT_CASOS_REVISIO_GEOLOCALITZACIO: string;
    USUARI_ID: (id: number) => string;
    CAMP_DETENCIO_ID: (id: number) => string;
    LLISTAT_PRESONS_CAMPS: string;
    LLISTAT_CAMPS: string;
    CAMP_CONCENTRACIO_ID: (id: number) => string;
    BIOGRAFIES_ID: (id: number) => string;
    REPRESALIAT_ID: (id: number) => string;
    LLISTAT_PENDENTS_AJUNTAMENT: string;
  };
  POST: {
    MUNICIPI: string;
    MUNICIPI_ESTAT: string;
    MUNICIPI_COMUNITAT: string;
    MUNICIPI_COMARCA: string;
    CAUSA_MORT: string;
    CATEGORIA_REPRESSIO: string;
    SUB_SECTOR_ECONOMIC: string;
    OFICI: string;
    CARREC_EMPRESA: string;
    ACUSACIO_JUDICIAL: string;
    BANDOL: string;
    CONDICIO_MILITAR: string;
    COS_MILITAR: string;
    ESPAI: string;
    ESTAT_CIVIL: string;
    NIVELL_ESTUDIS: string;
    SECTOR_ECONOMIC: string;
    LLIBRE_BIBLIOFRAFIA: string;
    ARXIU_CODI: string;
    EMPRESA: string;
    PROCEDIMENT_JUDICIAL: string;
    TIPUS_JUDICI: string;
    SENTENCIA: string;
    PENA: string;
    JUTJAT: string;
    MODALITAT_PRESO: string;
    MOTIU_DETENCIO: string;
    GRUP_REPRESSIO: string;
    PRESO: string;
    PRESO_DETENCIO: string;
    CAMP_CONCENTRACIO: string;
    BIOGRAFIES: string;
  };
  PUT: {
    MUNICIPI: string;
    MUNICIPI_ESTAT: string;
    MUNICIPI_COMUNITAT: string;
    MUNICIPI_COMARCA: string;
    CAUSA_MORT: string;
    CATEGORIA_REPRESSIO: string;
    SUB_SECTOR_ECONOMIC: string;
    OFICI: string;
    CARREC_EMPRESA: string;
    ACUSACIO_JUDICIAL: string;
    BANDOL: string;
    CONDICIO_MILITAR: string;
    COS_MILITAR: string;
    ESPAI: string;
    ESTAT_CIVIL: string;
    NIVELL_ESTUDIS: string;
    SECTOR_ECONOMIC: string;
    LLIBRE_BIBLIOFRAFIA: string;
    ARXIU_CODI: string;
    EMPRESA: string;
    PROCEDIMENT_JUDICIAL: string;
    TIPUS_JUDICI: string;
    SENTENCIA: string;
    PENA: string;
    JUTJAT: string;
    MODALITAT_PRESO: string;
    MOTIU_DETENCIO: string;
    GRUP_REPRESSIO: string;
    PRESO: string;
    PRESO_DETENCIO: string;
    CAMP_CONCENTRACIO: string;
    BIOGRAFIES: string;
  };
  DELETE: {
    MUNICIPI: string;
    MUNICIPI_ESTAT: string;
    MUNICIPI_COMUNITAT: string;
    MUNICIPI_COMARCA: string;
    CAUSA_MORT: string;
    CATEGORIA_REPRESSIO: string;
    SUB_SECTOR_ECONOMIC: string;
    OFICI: string;
    CARREC_EMPRESA: string;
    ACUSACIO_JUDICIAL: string;
    BANDOL: string;
    CONDICIO_MILITAR: string;
    COS_MILITAR: string;
    ESPAI: string;
    ESTAT_CIVIL: string;
    NIVELL_ESTUDIS: string;
    SECTOR_ECONOMIC: string;
    LLIBRE_BIBLIOFRAFIA: string;
    ARXIU_CODI: string;
    EMPRESA: string;
    PROCEDIMENT_JUDICIAL: string;
    TIPUS_JUDICI: string;
    SENTENCIA: string;
    PENA: string;
    JUTJAT: string;
    MODALITAT_PRESO: string;
    MOTIU_DETENCIO: string;
    GRUP_REPRESSIO: string;
    PRESO: string;
  };
};
