import { ApiUrls } from '../../types/apiTypes';

// Accede al dominio desde la variable de entorno
const BASE_URL = process.env.VITE_API_BASE_URL;
const API = 'api';

// Mapa de Endpoints
const ENDPOINTS = {
  CATEGORIES_REPRESSIO: 'categoriesRepressio',
  CATEGORIA_REPRESSIO: 'categoriaRepressio',
  MUNICIPI: 'municipi',
  MUNICIPI_ESTAT: 'estat',
  MUNICIPI_COMUNITAT: 'comunitat',
  MUNICIPI_COMARCA: 'comarca',
  CAUSA_MORT: 'causa_mort',
  SUB_SECTOR_ECONOMIC: 'sub_sector_economic',
  OFICI: 'ofici',
  CARREC_EMPRESA: 'carrec_empresa',
} as const;

// Mapa de recursos disponibles
const RESOURCES = {
  AUXILIARS: 'auxiliars',
  USERS: 'users',
} as const;

const TIPUS = {
  GET: 'get',
  POST: 'post',
  PUT: 'put',
  DELETE: 'delete',
} as const;

export const API_URLS: ApiUrls = {
  GET: {
    CATEGORIES_REPRESSIO: (lang: string) => `${BASE_URL}/api/auxiliars/get/categoriesRepressio?lang=${lang}`,
    MUNICIPI_ID: (id: number) => `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.GET}/${ENDPOINTS.MUNICIPI}?id=${id}`,
  },

  POST: {
    MUNICIPI: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.POST}/${ENDPOINTS.MUNICIPI}`,
    MUNICIPI_ESTAT: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.POST}/${ENDPOINTS.MUNICIPI_ESTAT}`,
    MUNICIPI_COMUNITAT: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.POST}/${ENDPOINTS.MUNICIPI_COMUNITAT}`,
    MUNICIPI_COMARCA: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.POST}/${ENDPOINTS.MUNICIPI_COMARCA}`,
    CAUSA_MORT: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.POST}/${ENDPOINTS.CAUSA_MORT}`,
    CATEGORIA_REPRESSIO: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.POST}/${ENDPOINTS.CATEGORIA_REPRESSIO}`,
    SUB_SECTOR_ECONOMIC: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.POST}/${ENDPOINTS.SUB_SECTOR_ECONOMIC}`,
    OFICI: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.POST}/${ENDPOINTS.OFICI}`,
    CARREC_EMPRESA: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.POST}/${ENDPOINTS.CARREC_EMPRESA}`,
  },

  PUT: {
    MUNICIPI: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.PUT}/${ENDPOINTS.MUNICIPI}`,
    MUNICIPI_ESTAT: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.PUT}/${ENDPOINTS.MUNICIPI_ESTAT}`,
    MUNICIPI_COMUNITAT: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.PUT}/${ENDPOINTS.MUNICIPI_COMUNITAT}`,
    MUNICIPI_COMARCA: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.PUT}/${ENDPOINTS.MUNICIPI_COMARCA}`,
    CAUSA_MORT: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.PUT}/${ENDPOINTS.CAUSA_MORT}`,
    CATEGORIA_REPRESSIO: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.PUT}/${ENDPOINTS.CATEGORIA_REPRESSIO}`,
    SUB_SECTOR_ECONOMIC: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.PUT}/${ENDPOINTS.SUB_SECTOR_ECONOMIC}`,
    OFICI: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.PUT}/${ENDPOINTS.OFICI}`,
    CARREC_EMPRESA: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.PUT}/${ENDPOINTS.CARREC_EMPRESA}`,
  },

  DELETE: {
    MUNICIPI: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.DELETE}/${ENDPOINTS.MUNICIPI}`,
    MUNICIPI_ESTAT: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.DELETE}/${ENDPOINTS.MUNICIPI_ESTAT}`,
    MUNICIPI_COMUNITAT: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.DELETE}/${ENDPOINTS.MUNICIPI_COMUNITAT}`,
    MUNICIPI_COMARCA: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.DELETE}/${ENDPOINTS.MUNICIPI_COMARCA}`,
    CAUSA_MORT: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.DELETE}/${ENDPOINTS.CAUSA_MORT}`,
    CATEGORIA_REPRESSIO: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.DELETE}/${ENDPOINTS.CATEGORIA_REPRESSIO}`,
    SUB_SECTOR_ECONOMIC: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.DELETE}/${ENDPOINTS.SUB_SECTOR_ECONOMIC}`,
    OFICI: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.DELETE}/${ENDPOINTS.OFICI}`,
    CARREC_EMPRESA: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.DELETE}/${ENDPOINTS.CARREC_EMPRESA}`,
  },
};
