import { ApiUrls } from '../../types/apiTypes';

// Accede al dominio desde la variable de entorno
const BASE_URL = process.env.VITE_API_BASE_URL;
const API = 'api';

// Mapa de Endpoints
export const ENDPOINTS = {
  CATEGORIES_REPRESSIO: 'categoriesRepressio',
  CATEGORIA_REPRESSIO: 'categoriaRepressio',
  MUNICIPI: 'municipi',
  MUNICIPI_ESTAT: 'estat',
  MUNICIPI_COMUNITAT: 'comunitat',
  MUNICIPI_COMARCA: 'comarca',
  CAUSA_MORT: 'causa_mort',
  SUB_SECTOR_ECONOMIC: 'sub_sector_economic',
  OFICI: 'ofici',
  CARREC_EMPRESA: 'carrec_empresa',
  ACUSACIO_JUDICIAL: 'acusacio',
  BANDOL: 'bandol',
  CONDICIO_MILITAR: 'condicio_militar',
  COS_MILITAR: 'cos_militar',
  ESPAI: 'espai',
  ESTAT_CIVIL: 'estat_civil',
  NIVELL_ESTUDIS: 'nivell_estudis',
  LLISTAT_SECTOR_ECONOMIC: 'sectors_economics',
  SECTOR_ECONOMIC: 'sector_economic',
} as const;

// Mapa de recursos disponibles
const RESOURCES = {
  AUXILIARS: 'auxiliars',
  USERS: 'users',
} as const;

const TIPUS = {
  GET: 'get',
  POST: 'post',
  PUT: 'put',
  DELETE: 'delete',
} as const;

export const API_URLS: ApiUrls = {
  GET: {
    CATEGORIES_REPRESSIO: (lang: string) => `${BASE_URL}/api/auxiliars/get/categoriesRepressio?lang=${lang}`,
    MUNICIPI_ID: (id: number) => `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.GET}/${ENDPOINTS.MUNICIPI}?id=${id}`,
    ESPAI_ID: (id: number) => `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.GET}/${ENDPOINTS.ESPAI}?id=${id}`,
    SUB_SECTOR_ID: (id: number) => `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.GET}/${ENDPOINTS.SUB_SECTOR_ECONOMIC}?id=${id}`,
    SECTOR_ECONOMIC: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.GET}/${ENDPOINTS.LLISTAT_SECTOR_ECONOMIC}`,
  },

  POST: {
    MUNICIPI: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.POST}/${ENDPOINTS.MUNICIPI}`,
    MUNICIPI_ESTAT: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.POST}/${ENDPOINTS.MUNICIPI_ESTAT}`,
    MUNICIPI_COMUNITAT: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.POST}/${ENDPOINTS.MUNICIPI_COMUNITAT}`,
    MUNICIPI_COMARCA: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.POST}/${ENDPOINTS.MUNICIPI_COMARCA}`,
    CAUSA_MORT: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.POST}/${ENDPOINTS.CAUSA_MORT}`,
    CATEGORIA_REPRESSIO: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.POST}/${ENDPOINTS.CATEGORIA_REPRESSIO}`,
    SUB_SECTOR_ECONOMIC: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.POST}/${ENDPOINTS.SUB_SECTOR_ECONOMIC}`,
    OFICI: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.POST}/${ENDPOINTS.OFICI}`,
    CARREC_EMPRESA: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.POST}/${ENDPOINTS.CARREC_EMPRESA}`,
    ACUSACIO_JUDICIAL: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.POST}/${ENDPOINTS.ACUSACIO_JUDICIAL}`,
    BANDOL: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.POST}/${ENDPOINTS.BANDOL}`,
    CONDICIO_MILITAR: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.POST}/${ENDPOINTS.CONDICIO_MILITAR}`,
    COS_MILITAR: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.POST}/${ENDPOINTS.COS_MILITAR}`,
    ESPAI: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.POST}/${ENDPOINTS.ESPAI}`,
    ESTAT_CIVIL: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.POST}/${ENDPOINTS.ESTAT_CIVIL}`,
    NIVELL_ESTUDIS: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.POST}/${ENDPOINTS.NIVELL_ESTUDIS}`,
    SECTOR_ECONOMIC: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.POST}/${ENDPOINTS.SECTOR_ECONOMIC}`,
  },

  PUT: {
    MUNICIPI: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.PUT}/${ENDPOINTS.MUNICIPI}`,
    MUNICIPI_ESTAT: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.PUT}/${ENDPOINTS.MUNICIPI_ESTAT}`,
    MUNICIPI_COMUNITAT: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.PUT}/${ENDPOINTS.MUNICIPI_COMUNITAT}`,
    MUNICIPI_COMARCA: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.PUT}/${ENDPOINTS.MUNICIPI_COMARCA}`,
    CAUSA_MORT: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.PUT}/${ENDPOINTS.CAUSA_MORT}`,
    CATEGORIA_REPRESSIO: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.PUT}/${ENDPOINTS.CATEGORIA_REPRESSIO}`,
    SUB_SECTOR_ECONOMIC: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.PUT}/${ENDPOINTS.SUB_SECTOR_ECONOMIC}`,
    OFICI: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.PUT}/${ENDPOINTS.OFICI}`,
    CARREC_EMPRESA: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.PUT}/${ENDPOINTS.CARREC_EMPRESA}`,
    ACUSACIO_JUDICIAL: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.PUT}/${ENDPOINTS.ACUSACIO_JUDICIAL}`,
    BANDOL: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.PUT}/${ENDPOINTS.BANDOL}`,
    CONDICIO_MILITAR: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.PUT}/${ENDPOINTS.CONDICIO_MILITAR}`,
    COS_MILITAR: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.PUT}/${ENDPOINTS.COS_MILITAR}`,
    ESPAI: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.PUT}/${ENDPOINTS.ESPAI}`,
    ESTAT_CIVIL: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.PUT}/${ENDPOINTS.ESTAT_CIVIL}`,
    NIVELL_ESTUDIS: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.PUT}/${ENDPOINTS.NIVELL_ESTUDIS}`,
    SECTOR_ECONOMIC: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.PUT}/${ENDPOINTS.SECTOR_ECONOMIC}`,
  },

  DELETE: {
    MUNICIPI: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.DELETE}/${ENDPOINTS.MUNICIPI}`,
    MUNICIPI_ESTAT: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.DELETE}/${ENDPOINTS.MUNICIPI_ESTAT}`,
    MUNICIPI_COMUNITAT: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.DELETE}/${ENDPOINTS.MUNICIPI_COMUNITAT}`,
    MUNICIPI_COMARCA: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.DELETE}/${ENDPOINTS.MUNICIPI_COMARCA}`,
    CAUSA_MORT: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.DELETE}/${ENDPOINTS.CAUSA_MORT}`,
    CATEGORIA_REPRESSIO: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.DELETE}/${ENDPOINTS.CATEGORIA_REPRESSIO}`,
    SUB_SECTOR_ECONOMIC: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.DELETE}/${ENDPOINTS.SUB_SECTOR_ECONOMIC}`,
    OFICI: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.DELETE}/${ENDPOINTS.OFICI}`,
    CARREC_EMPRESA: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.DELETE}/${ENDPOINTS.CARREC_EMPRESA}`,
    ACUSACIO_JUDICIAL: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.DELETE}/${ENDPOINTS.ACUSACIO_JUDICIAL}`,
    BANDOL: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.DELETE}/${ENDPOINTS.BANDOL}`,
    CONDICIO_MILITAR: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.DELETE}/${ENDPOINTS.CONDICIO_MILITAR}`,
    COS_MILITAR: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.DELETE}/${ENDPOINTS.COS_MILITAR}`,
    ESPAI: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.DELETE}/${ENDPOINTS.ESPAI}`,
    ESTAT_CIVIL: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.DELETE}/${ENDPOINTS.ESTAT_CIVIL}`,
    NIVELL_ESTUDIS: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.DELETE}/${ENDPOINTS.NIVELL_ESTUDIS}`,
    SECTOR_ECONOMIC: `${BASE_URL}/${API}/${RESOURCES.AUXILIARS}/${TIPUS.DELETE}/${ENDPOINTS.SECTOR_ECONOMIC}`,
  },
};
